--- 

- name: "create directory"
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "unarchive backend files"
  unarchive: 
    dest: /home/ubuntu/backend
    src: ~/project/artifact.tar.gz
    
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: Start PM2
  shell: |
    cd ~/backend
    npm install
    pm2 stop defaul
    pm2 start npm --name backend -- start
